[2021-03-07 19:02:50,948] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_3.save 2021-03-07T19:02:50.252322+00:00 [queued]>
[2021-03-07 19:02:50,955] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_3.save 2021-03-07T19:02:50.252322+00:00 [queued]>
[2021-03-07 19:02:50,955] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:02:50,955] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:02:50,955] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:02:50,965] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): save> on 2021-03-07T19:02:50.252322+00:00
[2021-03-07 19:02:50,969] {standard_task_runner.py:52} INFO - Started process 50 to run task
[2021-03-07 19:02:50,972] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_clickhouse_3', 'save', '2021-03-07T19:02:50.252322+00:00', '--job-id', '135', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_clickhouse_3/main.py', '--cfg-path', '/tmp/tmpwzsvq0nu', '--error-file', '/tmp/tmpjidfdria']
[2021-03-07 19:02:50,972] {standard_task_runner.py:77} INFO - Job 135: Subtask save
[2021-03-07 19:02:51,000] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_clickhouse_3.save 2021-03-07T19:02:50.252322+00:00 [running]> on host 020f66ce59e6
[2021-03-07 19:02:51,026] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_clickhouse_3
AIRFLOW_CTX_TASK_ID=save
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T19:02:50.252322+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T19:02:50.252322+00:00
[2021-03-07 19:02:51,106] {logging_mixin.py:104} INFO - [(datetime.datetime(2021, 3, 7, 19, 2, 51), '21.2.4.6')]
[2021-03-07 19:02:51,123] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_clickhouse_3, task_id=save, execution_date=20210307T190250, start_date=20210307T190250, end_date=20210307T190251
[2021-03-07 19:02:51,159] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:02:51,184] {local_task_job.py:146} INFO - Task exited with return code 0
