[2021-03-07 19:59:32,775] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_to_kafka_1.log 2021-03-07T19:59:31.437646+00:00 [queued]>
[2021-03-07 19:59:32,784] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_to_kafka_1.log 2021-03-07T19:59:31.437646+00:00 [queued]>
[2021-03-07 19:59:32,785] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:59:32,785] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:59:32,785] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:59:32,790] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): log> on 2021-03-07T19:59:31.437646+00:00
[2021-03-07 19:59:32,793] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2021-03-07 19:59:32,795] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'send_to_kafka_1', 'log', '2021-03-07T19:59:31.437646+00:00', '--job-id', '182', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/send_to_kafka_1/main.py', '--cfg-path', '/tmp/tmpjjoovech', '--error-file', '/tmp/tmp_3visshu']
[2021-03-07 19:59:32,796] {standard_task_runner.py:77} INFO - Job 182: Subtask log
[2021-03-07 19:59:32,819] {logging_mixin.py:104} INFO - Running <TaskInstance: send_to_kafka_1.log 2021-03-07T19:59:31.437646+00:00 [running]> on host 7531d0e32fd2
[2021-03-07 19:59:32,850] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=send_to_kafka_1
AIRFLOW_CTX_TASK_ID=log
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T19:59:31.437646+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T19:59:31.437646+00:00
[2021-03-07 19:59:32,850] {logging_mixin.py:104} INFO - Should be send in kafka
[2021-03-07 19:59:32,850] {logging_mixin.py:104} INFO - None
[2021-03-07 19:59:32,856] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=send_to_kafka_1, task_id=log, execution_date=20210307T195931, start_date=20210307T195932, end_date=20210307T195932
[2021-03-07 19:59:32,871] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:59:32,888] {local_task_job.py:146} INFO - Task exited with return code 0
