[2021-03-03 21:18:20,213] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.write_text_file 2021-03-03T21:18:19.248965+00:00 [queued]>
[2021-03-03 21:18:20,222] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.write_text_file 2021-03-03T21:18:19.248965+00:00 [queued]>
[2021-03-03 21:18:20,223] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:18:20,223] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 21:18:20,223] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:18:20,229] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): write_text_file> on 2021-03-03T21:18:19.248965+00:00
[2021-03-03 21:18:20,232] {standard_task_runner.py:52} INFO - Started process 47 to run task
[2021-03-03 21:18:20,234] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_minio_2', 'write_text_file', '2021-03-03T21:18:19.248965+00:00', '--job-id', '51', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_mino_2/main.py', '--cfg-path', '/tmp/tmp000oybor', '--error-file', '/tmp/tmpmg2s17b_']
[2021-03-03 21:18:20,235] {standard_task_runner.py:77} INFO - Job 51: Subtask write_text_file
[2021-03-03 21:18:20,258] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_minio_2.write_text_file 2021-03-03T21:18:19.248965+00:00 [running]> on host 4c61e128b408
[2021-03-03 21:18:20,289] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_minio_2
AIRFLOW_CTX_TASK_ID=write_text_file
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T21:18:19.248965+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T21:18:19.248965+00:00
[2021-03-03 21:18:20,290] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=local_minio
[2021-03-03 21:18:20,295] {base_aws.py:164} INFO - Credentials retrieved from extra_config
[2021-03-03 21:18:20,295] {base_aws.py:81} INFO - Creating session with aws_access_key_id=minio-access-key region_name=None
[2021-03-03 21:18:20,305] {base_aws.py:151} INFO - role_arn is None
[2021-03-03 21:18:20,353] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_minio_2, task_id=write_text_file, execution_date=20210303T211819, start_date=20210303T211820, end_date=20210303T211820
[2021-03-03 21:18:20,367] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-03 21:18:20,407] {local_task_job.py:146} INFO - Task exited with return code 0
