[2021-03-07 19:22:28,733] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_1.save 2021-03-07T19:22:28.344331+00:00 [queued]>
[2021-03-07 19:22:28,744] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_1.save 2021-03-07T19:22:28.344331+00:00 [queued]>
[2021-03-07 19:22:28,744] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:22:28,744] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:22:28,744] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:22:28,752] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): save> on 2021-03-07T19:22:28.344331+00:00
[2021-03-07 19:22:28,756] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2021-03-07 19:22:28,758] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_clickhouse_1', 'save', '2021-03-07T19:22:28.344331+00:00', '--job-id', '161', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_clickhouse_1/main.py', '--cfg-path', '/tmp/tmp0x1fextk', '--error-file', '/tmp/tmp_kz1qquh']
[2021-03-07 19:22:28,758] {standard_task_runner.py:77} INFO - Job 161: Subtask save
[2021-03-07 19:22:28,788] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_clickhouse_1.save 2021-03-07T19:22:28.344331+00:00 [running]> on host 020f66ce59e6
[2021-03-07 19:22:28,816] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_clickhouse_1
AIRFLOW_CTX_TASK_ID=save
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T19:22:28.344331+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T19:22:28.344331+00:00
[2021-03-07 19:22:28,881] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_clickhouse_1, task_id=save, execution_date=20210307T192228, start_date=20210307T192228, end_date=20210307T192228
[2021-03-07 19:22:28,906] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:22:28,931] {local_task_job.py:146} INFO - Task exited with return code 0
