[2021-03-07 19:45:13,767] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_to_kafka_1.send 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 19:45:13,777] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_to_kafka_1.send 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 19:45:13,777] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:45:13,777] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:45:13,777] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:45:13,789] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): send> on 2021-03-06T00:00:00+00:00
[2021-03-07 19:45:13,794] {standard_task_runner.py:52} INFO - Started process 52 to run task
[2021-03-07 19:45:13,798] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'send_to_kafka_1', 'send', '2021-03-06T00:00:00+00:00', '--job-id', '176', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/send_to_kafka_1/main.py', '--cfg-path', '/tmp/tmpq3lzd318', '--error-file', '/tmp/tmp1cob9vlz']
[2021-03-07 19:45:13,798] {standard_task_runner.py:77} INFO - Job 176: Subtask send
[2021-03-07 19:45:13,835] {logging_mixin.py:104} INFO - Running <TaskInstance: send_to_kafka_1.send 2021-03-06T00:00:00+00:00 [running]> on host 7531d0e32fd2
[2021-03-07 19:45:13,868] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=send_to_kafka_1
AIRFLOW_CTX_TASK_ID=send
AIRFLOW_CTX_EXECUTION_DATE=2021-03-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-06T00:00:00+00:00
[2021-03-07 19:45:13,878] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=send_to_kafka_1, task_id=send, execution_date=20210306T000000, start_date=20210307T194513, end_date=20210307T194513
[2021-03-07 19:45:13,902] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:45:13,930] {local_task_job.py:146} INFO - Task exited with return code 0
