[2021-03-07 11:24:15,347] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.generate 2021-03-07T11:24:14.320833+00:00 [queued]>
[2021-03-07 11:24:15,358] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.generate 2021-03-07T11:24:14.320833+00:00 [queued]>
[2021-03-07 11:24:15,359] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 11:24:15,359] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 11:24:15,359] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 11:24:15,364] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): generate> on 2021-03-07T11:24:14.320833+00:00
[2021-03-07 11:24:15,368] {standard_task_runner.py:52} INFO - Started process 52 to run task
[2021-03-07 11:24:15,372] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_minio_2', 'generate', '2021-03-07T11:24:14.320833+00:00', '--job-id', '90', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_minio_2/main.py', '--cfg-path', '/tmp/tmp63ujbg75', '--error-file', '/tmp/tmpiyox5fv5']
[2021-03-07 11:24:15,372] {standard_task_runner.py:77} INFO - Job 90: Subtask generate
[2021-03-07 11:24:15,399] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_minio_2.generate 2021-03-07T11:24:14.320833+00:00 [running]> on host b5d0ebb2b610
[2021-03-07 11:24:15,425] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_minio_2
AIRFLOW_CTX_TASK_ID=generate
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T11:24:14.320833+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T11:24:14.320833+00:00
[2021-03-07 11:24:15,441] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_minio_2, task_id=generate, execution_date=20210307T112414, start_date=20210307T112415, end_date=20210307T112415
[2021-03-07 11:24:15,460] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-07 11:24:15,504] {local_task_job.py:146} INFO - Task exited with return code 0
