[2021-03-07 19:16:05,115] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_2.save 2021-03-07T19:16:04.422833+00:00 [queued]>
[2021-03-07 19:16:05,122] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_2.save 2021-03-07T19:16:04.422833+00:00 [queued]>
[2021-03-07 19:16:05,122] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:16:05,122] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:16:05,122] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:16:05,132] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): save> on 2021-03-07T19:16:04.422833+00:00
[2021-03-07 19:16:05,136] {standard_task_runner.py:52} INFO - Started process 54 to run task
[2021-03-07 19:16:05,138] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_clickhouse_2', 'save', '2021-03-07T19:16:04.422833+00:00', '--job-id', '150', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_clickhouse_2/main.py', '--cfg-path', '/tmp/tmpimxdxb7a', '--error-file', '/tmp/tmp5rl0kec5']
[2021-03-07 19:16:05,139] {standard_task_runner.py:77} INFO - Job 150: Subtask save
[2021-03-07 19:16:05,165] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_clickhouse_2.save 2021-03-07T19:16:04.422833+00:00 [running]> on host 020f66ce59e6
[2021-03-07 19:16:05,189] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_clickhouse_2
AIRFLOW_CTX_TASK_ID=save
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T19:16:04.422833+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T19:16:04.422833+00:00
[2021-03-07 19:16:05,249] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_clickhouse_2, task_id=save, execution_date=20210307T191604, start_date=20210307T191605, end_date=20210307T191605
[2021-03-07 19:16:05,269] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:16:05,311] {local_task_job.py:146} INFO - Task exited with return code 0
